#!/bin/sh

COMMIT_MSG_FILE=$1

# Parses JIRA-Ref for insertion into message footer from branch name in this style:
# {JIRA issue ID}_branch_description
# ex: OSI-29_static-site-skeleton -> JIRA-Ref: OSI-29
JIRA_REF=`git branch --show | awk -F'_' '{print $1}'`

echo "\n\nJIRA-Ref: $JIRA_REF" >> "$COMMIT_MSG_FILE"